services:
  - type: web
    name: ovi
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn ovi.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ovi.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        sync: false  # Set this in Render's dashboard for security
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        sync: false  # Set this in Render's dashboard
