services:
  - type: web
    name: ovi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ovi.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ovi.settings
      - key: PYTHON_VERSION
        value: 3.11
